(* This file was auto-generated by 'cycletbl_compare.py v1.0'*)
(* with the following input files: 'gctmain.h' and 'gctserpt.h'*)
(* Roger Logan, Anora'*)
(* DATE RUN: 2013-03-11 17:40:25.235269'*)
(* OS: ('Linux', 'lindesk39.dal.design.ti.com', '2.6.16.60-0.83.2-xen', '#1 SMP Fri Sep 2 13:49:16 UTC 2011', 'x86_64')*)

	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           SPCLKXdrive5WF,     CLKX0    );
	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           EXTDRdrive5WF,      DR0      );
	CycleSetMD( DWWSP5Cycle,    ContinueWF,         FSRdriveWF,         FSR0     );
	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           SPCLKRdrive5WF,     CLKR0    );
	CycleSetMD( DWWSP5Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DWWSP4Cycle,    ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( DWWSP4Cycle,    ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( DWWSP4Cycle,    ContinueWF,         FSXdriveWF,         FSX0     );
	CycleSetMD( DWWSP4Cycle,    EXTDXstrobe4WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DWRSP4Cycle,    ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( DWRSP4Cycle,    ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( DWRSP4Cycle,    ContinueWF,         FSXdriveWF,         FSX0     );
	CycleSetMD( DWRSP4Cycle,    EXTDXstrobe4WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DW1SP4Cycle,    ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( DW1SP4Cycle,    ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( DW1SP4Cycle,    ContinueWF,         FSXdriveWF,         FSX0     );
	CycleSetMD( DW1SP4Cycle,    EXTDXstrobe4WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DW1SP1Cycle,    ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DW1SP1Cycle,    ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DW1SP1Cycle,    ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DW1SP1Cycle,    EXTDXstrobe1WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DWRSP1Cycle,    ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DWRSP1Cycle,    ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DWRSP1Cycle,    ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DWRSP1Cycle,    EXTDXstrobe1WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DWWSP1AaCycle,  ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DWWSP1AaCycle,  ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DWWSP1AaCycle,  ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DWWSP1AaCycle,  ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DWWSP1AaCycle,  EXTDXAastrobe1WF,   EXTDXdriveWF,       DX0      );

	CycleSetMD( DW1Cycle,       FSXstrobeWF,        FSXdriveWF,         FSX0     );
	CycleSetMD( DW1Cycle,       FSRstrobeWF,        FSRdriveWF,         FSR0     );
	CycleSetMD( DW1Cycle,       CLKXstrobeWF,       CLKXdriveWF,        CLKX0    );
	CycleSetMD( DW1Cycle,       CLKRstrobeWF,       CLKRdriveWF,        CLKR0    );
	CycleSetMD( DW1Cycle,       DRstrobeWF,         DRdriveWF,          DR0      );
	CycleSetMD( DW1Cycle,       DXstrobeWF,         DXdriveWF,          DX0      );

	CycleSetMD( DWWSP1Cycle,    ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DWWSP1Cycle,    ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DWWSP1Cycle,    ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DWWSP1Cycle,    EXTDXstrobe1WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( TDDXZCycle,     ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( TDDXZCycle,     DBUSstrobeWF,       DBUSdriveWF,        DBUS     );
	CycleSetMD( TDDXZCycle,     ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( TDDXZCycle,     ABUSwrtbgnstrobeWF, ABUSstrobeWF,       ABUS     );
	CycleSetMD( TDDXZCycle,     ContinueWF,         FSXdriveWF,         FSX0     );

	CycleSetMD( DW2SP4Cycle,    ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( DW2SP4Cycle,    ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( DW2SP4Cycle,    ContinueWF,         FSXdriveWF,         FSX0     );
	CycleSetMD( DW2SP4Cycle,    EXTDXstrobe4WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DW2Cycle,       FSXstrobeWF,        FSXdriveWF,         FSX0     );
	CycleSetMD( DW2Cycle,       FSRstrobeWF,        FSRdriveWF,         FSR0     );
	CycleSetMD( DW2Cycle,       CLKXstrobeWF,       CLKXdriveWF,        CLKX0    );
	CycleSetMD( DW2Cycle,       CLKRstrobeWF,       CLKRdriveWF,        CLKR0    );
	CycleSetMD( DW2Cycle,       DRstrobeWF,         DRdriveWF,          DR0      );
	CycleSetMD( DW2Cycle,       DXstrobeWF,         DXdriveWF,          DX0      );

	CycleSetMD( DW2SP1Cycle,    ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DW2SP1Cycle,    ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DW2SP1Cycle,    ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DW2SP1Cycle,    EXTDXstrobe1WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DRDCycle,       FSXstrobeWF,        FSXdriveWF,         FSX0     );
	CycleSetMD( DRDCycle,       FSRstrobeWF,        FSRdriveWF,         FSR0     );
	CycleSetMD( DRDCycle,       DRstrobeWF,         DRdriveWF,          DR0      );
	CycleSetMD( DRDCycle,       CLKRstrobeWF,       CLKRdriveWF,        CLKR0    );
	CycleSetMD( DRDCycle,       INT_BdriveWF,       INT_driveWF,        EXTINT   );
	CycleSetMD( DRDCycle,       CLKXstrobeWF,       CLKXdriveWF,        CLKX0    );
	CycleSetMD( DRDCycle,       DXstrobeWF,         DXdriveWF,          DX0      );

	CycleSetMD( DWRSP2Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         EXFSRdrive2WF,      FSR0     );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         SPCLKXdrive2WF,     CLKX0    );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         SPCLKRdrive2WF,     CLKR0    );
	CycleSetMD( DWRSP2Cycle,    ALLoffWF,           EXTDRdrive2WF,      DR0      );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DW1SP2Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         EXFSRdrive2WF,      FSR0     );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         SPCLKXdrive2WF,     CLKX0    );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         SPCLKRdrive2WF,     CLKR0    );
	CycleSetMD( DW1SP2Cycle,    ALLoffWF,           EXTDRdrive2WF,      DR0      );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DWWCycle,       FSXstrobeWF,        FSXdriveWF,         FSX0     );
	CycleSetMD( DWWCycle,       FSRstrobeWF,        FSRdriveWF,         FSR0     );
	CycleSetMD( DWWCycle,       CLKXstrobeWF,       CLKXdriveWF,        CLKX0    );
	CycleSetMD( DWWCycle,       CLKRstrobeWF,       CLKRdriveWF,        CLKR0    );
	CycleSetMD( DWWCycle,       DRstrobeWF,         DRdriveWF,          DR0      );
	CycleSetMD( DWWCycle,       DXstrobeWF,         DXdriveWF,          DX0      );

	CycleSetMD( DRDSP1Cycle,    ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DRDSP1Cycle,    ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DRDSP1Cycle,    ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DRDSP1Cycle,    EXTDXstrobe1WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           SPCLKXdrive5WF,     CLKX0    );
	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           EXTDRdrive5WF,      DR0      );
	CycleSetMD( DW1SP5Cycle,    ContinueWF,         FSRdriveWF,         FSR0     );
	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           SPCLKRdrive5WF,     CLKR0    );
	CycleSetMD( DW1SP5Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           SPCLKXdrive5WF,     CLKX0    );
	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           EXTDRdrive5WF,      DR0      );
	CycleSetMD( DWRSP5Cycle,    ContinueWF,         FSRdriveWF,         FSR0     );
	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           SPCLKRdrive5WF,     CLKR0    );
	CycleSetMD( DWRSP5Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DRDSP4Cycle,    ALLoffWF,           SPCLKXdrive4WF,     CLKX0    );
	CycleSetMD( DRDSP4Cycle,    ALLoffWF,           SPCLKRdrive4WF,     CLKR0    );
	CycleSetMD( DRDSP4Cycle,    ContinueWF,         FSXdriveWF,         FSX0     );
	CycleSetMD( DRDSP4Cycle,    EXTDXstrobe4WF,     EXTDXdriveWF,       DX0      );

	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           SPCLKXdrive5WF,     CLKX0    );
	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           EXTDRdrive5WF,      DR0      );
	CycleSetMD( DRDSP5Cycle,    ContinueWF,         FSRdriveWF,         FSR0     );
	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           SPCLKRdrive5WF,     CLKR0    );
	CycleSetMD( DRDSP5Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DW2SP2Cycle,    ContinueWF,         SPCLKXdrive2WF,     CLKX0    );
	CycleSetMD( DW2SP2Cycle,    ALLoffWF,           EXTDRdrive2WF,      DR0      );
	CycleSetMD( DW2SP2Cycle,    ContinueWF,         EXFSRdrive2WF,      FSR0     );
	CycleSetMD( DW2SP2Cycle,    ContinueWF,         SPCLKRdrive2WF,     CLKR0    );
	CycleSetMD( DW2SP2Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DRDSP1ACycle,   ALLoffWF,           SPCLKXdrive1WF,     CLKX0    );
	CycleSetMD( DRDSP1ACycle,   ContinueWF,         EXFSRdrive1WF,      FSR0     );
	CycleSetMD( DRDSP1ACycle,   ALLoffWF,           SPCLKRdrive1WF,     CLKR0    );
	CycleSetMD( DRDSP1ACycle,   EXTDXAstrobe1WF,    EXTDXdriveWF,       DX0      );

	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           SPCLKXdrive5WF,     CLKX0    );
	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           EXTDRdrive5WF,      DR0      );
	CycleSetMD( DW2SP5Cycle,    ContinueWF,         FSRdriveWF,         FSR0     );
	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           SPCLKRdrive5WF,     CLKR0    );
	CycleSetMD( DW2SP5Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DWRCycle,       FSXstrobeWF,        FSXdriveWF,         FSX0     );
	CycleSetMD( DWRCycle,       FSRstrobeWF,        FSRdriveWF,         FSR0     );
	CycleSetMD( DWRCycle,       CLKXstrobeWF,       CLKXdriveWF,        CLKX0    );
	CycleSetMD( DWRCycle,       CLKRstrobeWF,       CLKRdriveWF,        CLKR0    );
	CycleSetMD( DWRCycle,       DRstrobeWF,         DRdriveWF,          DR0      );
	CycleSetMD( DWRCycle,       DXstrobeWF,         DXdriveWF,          DX0      );

	CycleSetMD( DWWSP2Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         EXFSRdrive2WF,      FSR0     );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         SPCLKXdrive2WF,     CLKX0    );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         SPCLKRdrive2WF,     CLKR0    );
	CycleSetMD( DWWSP2Cycle,    ALLoffWF,           EXTDRdrive2WF,      DR0      );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

	CycleSetMD( DRDSP2Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         EXFSRdrive2WF,      FSR0     );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         SPCLKXdrive2WF,     CLKX0    );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         SPCLKRdrive2WF,     CLKR0    );
	CycleSetMD( DRDSP2Cycle,    ALLoffWF,           EXTDRdrive2WF,      DR0      );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         EXTDXdriveWF,       DX0      );

