(* This file was auto-generated by 'cycletbl_compare.py v1.0'*)
(* with the following input files: 'gctmain.h' and 'gctserpt.h'*)
(* Roger Logan, Anora'*)
(* DATE RUN: 2013-03-11 17:40:25.239062'*)
(* OS: ('Linux', 'lindesk39.dal.design.ti.com', '2.6.16.60-0.83.2-xen', '#1 SMP Fri Sep 2 13:49:16 UTC 2011', 'x86_64')*)

	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           EXSPCLKXdrive5WF,   CLKX0    );
	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           EXDRdrive5WF,       DR0      );
	CycleSetMD( DWWSP5Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DWWSP5Cycle,    ALLoffWF,           EXSPCLKRdrive5WF,   CLKR0    );
	CycleSetMD( DWWSP5Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DWWSP4Cycle,    ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( DWWSP4Cycle,    ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( DWWSP4Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DWWSP4Cycle,    EXDXstrobe4WF,      ContinueWF,         DX0      );

	CycleSetMD( DWRSP4Cycle,    ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( DWRSP4Cycle,    ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( DWRSP4Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DWRSP4Cycle,    EXDXstrobe4WF,      ContinueWF,         DX0      );

	CycleSetMD( DW1SP4Cycle,    ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( DW1SP4Cycle,    ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( DW1SP4Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DW1SP4Cycle,    EXDXstrobe4WF,      ContinueWF,         DX0      );

	CycleSetMD( DW1SP1Cycle,    ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DW1SP1Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DW1SP1Cycle,    ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DW1SP1Cycle,    EXDXstrobe1WF,      ContinueWF,         DX0      );

	CycleSetMD( DWRSP1Cycle,    ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DWRSP1Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DWRSP1Cycle,    ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DWRSP1Cycle,    EXDXstrobe1WF,      ContinueWF,         DX0      );

	CycleSetMD( DWWSP1AaCycle,  ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DWWSP1AaCycle,  ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DWWSP1AaCycle,  ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DWWSP1AaCycle,  ContinueWF,         EXFSXadrive1WF,     FSX0     );
	CycleSetMD( DWWSP1AaCycle,  EXDXAastrobe1WF,    ContinueWF,         DX0      );

	CycleSetMD( DW1Cycle,       FSXGPIOstrobeWF,    FSXGPIOdriveWF,     FSX0     );
	CycleSetMD( DW1Cycle,       FSRGPIOstrobeWF,    FSXGPIOdriveWF,     FSR0     );
	CycleSetMD( DW1Cycle,       CLKXGPIOstrobeWF,   CLKXGPIOdriveWF,    CLKX0    );
	CycleSetMD( DW1Cycle,       CLKRGPIOstrobeWF,   CLKRGPIOdriveWF,    CLKR0    );
	CycleSetMD( DW1Cycle,       DRGPIOstrobeWF,     DRGPIOdriveWF,      DR0      );
	CycleSetMD( DW1Cycle,       DXGPIOstrobeWF,     DXGPIOdriveWF,      DX0      );

	CycleSetMD( DWWSP1Cycle,    ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DWWSP1Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DWWSP1Cycle,    ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DWWSP1Cycle,    EXDXstrobe1WF,      ContinueWF,         DX0      );

	CycleSetMD( TDDXZCycle,     ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( TDDXZCycle,     DBUSendstrobeWF,    ContinueWF,         DBUS     );
	CycleSetMD( TDDXZCycle,     ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( TDDXZCycle,     ABUSwrtendstrobeWF, ContinueWF,         ABUS     );
	CycleSetMD( TDDXZCycle,     ContinueWF,         ContinueWF,         FSX0     );

	CycleSetMD( DW2SP4Cycle,    ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( DW2SP4Cycle,    ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( DW2SP4Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DW2SP4Cycle,    EXDXstrobe4WF,      ContinueWF,         DX0      );

	CycleSetMD( DW2Cycle,       FSXGPIOstrobeWF,    FSXGPIOdriveWF,     FSX0     );
	CycleSetMD( DW2Cycle,       FSRGPIOstrobeWF,    FSXGPIOdriveWF,     FSR0     );
	CycleSetMD( DW2Cycle,       CLKXGPIOstrobeWF,   CLKXGPIOdriveWF,    CLKX0    );
	CycleSetMD( DW2Cycle,       CLKRGPIOstrobeWF,   CLKRGPIOdriveWF,    CLKR0    );
	CycleSetMD( DW2Cycle,       DRGPIOstrobeWF,     DRGPIOdriveWF,      DR0      );
	CycleSetMD( DW2Cycle,       DXGPIOstrobeWF,     DXGPIOdriveWF,      DX0      );

	CycleSetMD( DW2SP1Cycle,    ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DW2SP1Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DW2SP1Cycle,    ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DW2SP1Cycle,    EXDXstrobe1WF,      ContinueWF,         DX0      );

	CycleSetMD( DRDCycle,       FSXGPIOstrobeWF,    FSXGPIOdriveWF,     FSX0     );
	CycleSetMD( DRDCycle,       FSRGPIOstrobeWF,    FSRGPIOdriveWF,     FSR0     );
	CycleSetMD( DRDCycle,       DRGPIOstrobeWF,     DRGPIOdriveWF,      DR0      );
	CycleSetMD( DRDCycle,       CLKRGPIOstrobeWF,   CLKRGPIOdriveWF,    CLKR0    );
	CycleSetMD( DRDCycle,       ALLoffWF,           INT_driveWF,        EXTINT   );
	CycleSetMD( DRDCycle,       CLKXGPIOstrobeWF,   CLKXGPIOdriveWF,    CLKX0    );
	CycleSetMD( DRDCycle,       DXGPIOstrobeWF,     DXGPIOdriveWF,      DX0      );

	CycleSetMD( DWRSP2Cycle,    ContinueWF,         EXFSXdrive2WF,      FSX0     );
	CycleSetMD( DWRSP2Cycle,    EXFSRVdrive2WF,     EXFSRFdrive2WF,     FSR0     );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         EXSPCLKXdrive2WF,   CLKX0    );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         EXSPCLKRdrive2WF,   CLKR0    );
	CycleSetMD( DWRSP2Cycle,    ALLoffWF,           EXDRdrive2WF,       DR0      );
	CycleSetMD( DWRSP2Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DW1SP2Cycle,    ContinueWF,         EXFSXdrive2WF,      FSX0     );
	CycleSetMD( DW1SP2Cycle,    EXFSRVdrive2WF,     EXFSRFdrive2WF,     FSR0     );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         EXSPCLKXdrive2WF,   CLKX0    );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         EXSPCLKRdrive2WF,   CLKR0    );
	CycleSetMD( DW1SP2Cycle,    ALLoffWF,           EXDRdrive2WF,       DR0      );
	CycleSetMD( DW1SP2Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DWWCycle,       FSXGPIOstrobeWF,    FSXGPIOdriveWF,     FSX0     );
	CycleSetMD( DWWCycle,       FSRGPIOstrobeWF,    FSRGPIOdriveWF,     FSR0     );
	CycleSetMD( DWWCycle,       CLKXGPIOstrobeWF,   CLKXGPIOdriveWF,    CLKX0    );
	CycleSetMD( DWWCycle,       CLKRGPIOstrobeWF,   CLKRGPIOdriveWF,    CLKR0    );
	CycleSetMD( DWWCycle,       DRGPIOstrobeWF,     DRGPIOdriveWF,      DR0      );
	CycleSetMD( DWWCycle,       DXGPIOstrobeWF,     DXGPIOdriveWF,      DX0      );

	CycleSetMD( DRDSP1Cycle,    ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DRDSP1Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DRDSP1Cycle,    ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DRDSP1Cycle,    EXDXstrobe1WF,      ContinueWF,         DX0      );

	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           EXSPCLKXdrive5WF,   CLKX0    );
	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           EXDRdrive5WF,       DR0      );
	CycleSetMD( DW1SP5Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DW1SP5Cycle,    ALLoffWF,           EXSPCLKRdrive5WF,   CLKR0    );
	CycleSetMD( DW1SP5Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           EXSPCLKXdrive5WF,   CLKX0    );
	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           EXDRdrive5WF,       DR0      );
	CycleSetMD( DWRSP5Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DWRSP5Cycle,    ALLoffWF,           EXSPCLKRdrive5WF,   CLKR0    );
	CycleSetMD( DWRSP5Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DRDSP4Cycle,    ALLoffWF,           EXSPCLKXdrive4WF,   CLKX0    );
	CycleSetMD( DRDSP4Cycle,    ALLoffWF,           EXSPCLKRdrive4WF,   CLKR0    );
	CycleSetMD( DRDSP4Cycle,    ContinueWF,         ContinueWF,         FSX0     );
	CycleSetMD( DRDSP4Cycle,    EXDXstrobe4WF,      ContinueWF,         DX0      );

	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           EXSPCLKXdrive5WF,   CLKX0    );
	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           EXDRdrive5WF,       DR0      );
	CycleSetMD( DRDSP5Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DRDSP5Cycle,    ALLoffWF,           EXSPCLKRdrive5WF,   CLKR0    );
	CycleSetMD( DRDSP5Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DW2SP2Cycle,    ContinueWF,         EXSPCLKXdrive2WF,   CLKX0    );
	CycleSetMD( DW2SP2Cycle,    ALLoffWF,           EXDRdrive2WF,       DR0      );
	CycleSetMD( DW2SP2Cycle,    EXFSRVdrive2WF,     EXFSRFdrive2WF,     FSR0     );
	CycleSetMD( DW2SP2Cycle,    ContinueWF,         EXSPCLKRdrive2WF,   CLKR0    );
	CycleSetMD( DW2SP2Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DRDSP1ACycle,   ALLoffWF,           EXSPCLKXdrive1WF,   CLKX0    );
	CycleSetMD( DRDSP1ACycle,   ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DRDSP1ACycle,   ALLoffWF,           EXSPCLKRdrive1WF,   CLKR0    );
	CycleSetMD( DRDSP1ACycle,   EXDXAstrobe1WF,     ContinueWF,         DX0      );

	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           EXSPCLKXdrive5WF,   CLKX0    );
	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           EXDRdrive5WF,       DR0      );
	CycleSetMD( DW2SP5Cycle,    ContinueWF,         ContinueWF,         FSR0     );
	CycleSetMD( DW2SP5Cycle,    ALLoffWF,           EXSPCLKRdrive5WF,   CLKR0    );
	CycleSetMD( DW2SP5Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DWRCycle,       FSXGPIOstrobeWF,    FSXGPIOdriveWF,     FSX0     );
	CycleSetMD( DWRCycle,       FSRGPIOstrobeWF,    FSXGPIOdriveWF,     FSR0     );
	CycleSetMD( DWRCycle,       CLKXGPIOstrobeWF,   CLKXGPIOdriveWF,    CLKX0    );
	CycleSetMD( DWRCycle,       CLKRGPIOstrobeWF,   CLKRGPIOdriveWF,    CLKR0    );
	CycleSetMD( DWRCycle,       DRGPIOstrobeWF,     DRGPIOdriveWF,      DR0      );
	CycleSetMD( DWRCycle,       DXGPIOstrobeWF,     DXGPIOdriveWF,      DX0      );

	CycleSetMD( DWWSP2Cycle,    ContinueWF,         EXFSXdrive2WF,      FSX0     );
	CycleSetMD( DWWSP2Cycle,    EXFSRVdrive2WF,     EXFSRFdrive2WF,     FSR0     );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         EXSPCLKXdrive2WF,   CLKX0    );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         EXSPCLKRdrive2WF,   CLKR0    );
	CycleSetMD( DWWSP2Cycle,    ALLoffWF,           EXDRdrive2WF,       DR0      );
	CycleSetMD( DWWSP2Cycle,    ContinueWF,         ContinueWF,         DX0      );

	CycleSetMD( DRDSP2Cycle,    ContinueWF,         EXFSXdrive2WF,      FSX0     );
	CycleSetMD( DRDSP2Cycle,    EXFSRVdrive2WF,     EXFSRFdrive2WF,     FSR0     );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         EXSPCLKXdrive2WF,   CLKX0    );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         EXSPCLKRdrive2WF,   CLKR0    );
	CycleSetMD( DRDSP2Cycle,    ALLoffWF,           EXDRdrive2WF,       DR0      );
	CycleSetMD( DRDSP2Cycle,    ContinueWF,         ContinueWF,         DX0      );

