
procedure DeviceTableSet;
var
    devicetablename,nameofhost     : String;
const
    MINV    = -2v;
    MAXV    =  9v;
    MINI    = -50ma;
    MAXI    =  50ma;
    MINVCC  = -2v;
    MAXVCC  = 11v;
    MINVCCI = -500000;
    MAXVCCI = 1500000;
begin
HostNameGet(nameofhost);
case TIDeviceType of
 C57_PGE :
  begin
   DeviceTableOpen;
   devicetablename:= 'PGEDeviceTable';
   DeviceTableSetName(devicetablename);
   PinSetMP    (NHINT     ,   1 ,  63 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (EMU0      ,   2 ,  24 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (EMU1      ,   3 ,  64 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TOUT      ,   6 , 103 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BCLKX     ,   7 , 104 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (CLKX      ,   8 ,  25 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HPISEL    ,   9 ,  66 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BFSR      ,  10 ,  26 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BCLKR     ,  11 ,  65 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NRS       ,  12 , 106 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (READY     ,  13 ,  27 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHOLD     ,  14 , 105 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NBIO      ,  17 ,  28 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NIAQ      ,  18 ,  68 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TRST      ,  19 ,  67 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (MPNMC     ,  22 , 107 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D15       ,  23 ,  30 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D14       ,  24 ,  29 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D13       ,  25 , 108 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D12       ,  26 ,  69 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D11       ,  27 ,  70 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D10       ,  28 , 109 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D9        ,  29 , 110 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D8        ,  30 ,  31 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D7        ,  35 ,  32 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D6        ,  36 ,  72 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D5        ,  37 ,  71 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D4        ,  38 ,  33 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D3        ,  39 ,  34 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D2        ,  40 ,  35 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D1        ,  41 ,  74 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (D0        ,  42 ,  73 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HCNTL0    ,  43 ,  76 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TMS       ,  44 ,  75 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HCNTL1    ,  45 ,  36 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TCK       ,  48 ,  37 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NMTESTEN  , 131 ,  38 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHRW      ,  51 ,  78 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NINT1     ,  52 ,  39 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NINT2     ,  53 ,  77 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NINT3     ,  54 ,  79 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NINT4     ,  55 ,  80 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HBIL      ,  56 ,  40 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NNMI      ,  57 ,   1 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (DR        ,  58 ,   2 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BDR       ,  59 ,  41 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (FSR       ,  60 ,  42 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (CLKR      ,  61 ,  81 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHAS      ,  64 ,  82 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHCS      ,  65 ,  83 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A0        ,  67 ,   3 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A1        ,  68 ,  84 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A2        ,  69 ,  43 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A3        ,  70 ,   5 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A4        ,  71 ,  44 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A5        ,  72 ,   4 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A6        ,  73 ,  45 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A7        ,  74 ,   6 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A8        ,  75 ,  85 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A9        ,  76 ,  46 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHDS2     ,  79 ,   7 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHDS1     ,  80 ,  86 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TDI       ,  81 ,   8 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (CLKMOD1   ,  84 ,  87 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A10       ,  85 ,  48 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A11       ,  86 ,  47 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A12       ,  87 ,  88 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A13       ,  88 ,  49 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A14       ,  89 ,  10 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (A15       ,  90 ,  90 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HRDY      ,  92 ,  11 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD0       ,  93 ,  12 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMuxMP (NRD       ,  94 ,  51 , 52 ,  O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD1       ,  95 ,  91 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NWE       ,  96 ,  92 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD2       ,  99 ,  13 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NDS       , 100 ,  54 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NIS       , 101 ,  53 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NPS       , 102 ,  14 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (RNW       , 103 ,  15 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMuxMP (NSTRB     , 104 ,  93 , 94 , IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD3       , 105 ,  56 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NBR       , 106 ,  55 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NOLCM     , 129 ,  16 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (CLKMOD3   , 107 ,  57 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMuxMP (X2CLKIN   , 108 ,  17 , 18 ,  I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (X1        , 109 ,  95 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NOLCS     , 130 ,  97 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (TDO       , 111 ,  96 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD4       , 114 ,  98 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (CLKMOD2   , 115 ,  59 ,       I, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD5       , 116 ,  20 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (FSX       , 117 ,  19 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD6       , 118 , 100 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BFSX      , 119 ,  99 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (HD7       , 120 ,  60 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (DX        , 121 ,  21 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (BDX       , 122 ,  22 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NHOLDA    , 123 ,  61 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (XF        , 124 ,  62 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMuxMP (CLKOUT    , 125 , 101 ,102 ,  O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (NIACK     , 132 ,  23 ,       O, MINV,   MAXV,   MINI,   MAXI );
   PinSetMP    (SYNC      , 133 , 111 ,      IO, MINV,   MAXV,   MINI,   MAXI );
   PinSetSupply(CVdd     ,  77 , Supply1 ,MINVCC, MAXVCC, MINVCCI, MAXVCCI );
   PinSetSupply(DVdd     ,  16 , Supply2 ,MINVCC, MAXVCC, MINVCCI, MAXVCCI );
   PinSetSupply(CVss     , 20 , Ground ,    0  ,    0  ,    0   ,    0);
   PinSetSupply(DVss     ,  4 , Ground ,    0  ,    0  ,    0   ,    0);
  DeviceTableClose;
  end;
end;

PinListSet(EVENPINS,EMU0,TOUT,CLKX,BFSR,NRS,NHOLD,NIAQ,MPNMC,D14,D12,D10,D8,D6,D4,D2,D0,TMS,TCK,NINT1,NINT3,HBIL,DR,FSR,NHAS,A0,A2,A4,A6,A8,NHDS2,TDI,A10,A12,A14,HRDY,NRD,NWE,NDS,NPS,NSTRB,NBR,X2CLKIN,TDO,CLKMOD2,FSX,BFSX,DX,NHOLDA,CLKOUT);
PinListSet(ODDPINS,NHINT,EMU1,BCLKX,HPISEL,BCLKR,READY,NBIO,TRST,D15,D13,D11,D9,D7,D5,D3,D1,HCNTL0,HCNTL1,NHRW,NINT2,NINT4,NNMI,BDR,CLKR,NHCS,A1,A3,A5,A7,A9,NHDS1,CLKMOD1,A11,A13,A15,HD0,HD1,HD2,NIS,RNW,HD3,CLKMOD3,X1,HD4,HD5,HD6,HD7,BDX,XF,NIACK);
PinListSet(ALLPINS,EVENPINS,ODDPINS);
PinListSet(NOTESTINS,NMTESTEN,NOLCM,NOLCS,SYNC);
PinListSet(SHORTSPINS,ALLPINS);
PinListSet(ABUS,A15,A14,A13,A12,A11,A10,A9,A8,A7,A6,A5,A4,A3,A2,A1,A0);
PinListSet(DBUS,D15,D14,D13,D12,D11,D10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0);
PinListSet(HPI_DBUS,HD0,HD1,HD2,HD3,HD4,HD5,HD6,HD7);
PinListSet(HPIPINS,HD0,HD1,HD2,HD3,HD4,HD5,HD6,HD7,HPISEL,HRDY,NHCS,NHAS,NHINT,HBIL,NHRW,HCNTL1,HCNTL0,NHDS2,NHDS1);
PinListSet(HPI_INS,HCNTL0,HCNTL1,NHDS1,NHDS2,NHRW,NHAS,NHCS,HBIL,HPISEL);
PinListSet(HPI_IOS,HD0,HD1,HD2,HD3,HD4,HD5,HD6,HD7);
PinListSet(HPI_OUTS,NHINT,HRDY);
PinListSet(INUPS,TMS,TCK,TDI,HCNTL1,HCNTL0,NHRW,NHCS,NHDS1,HBIL,NHAS,NHDS2)
PinListSet(INDOWNS,TRST,HPISEL)
PinListSet(ABTIME,NPS,NDS,NIS,NBR,RNW);
PinListSet(NINTS,NINT4,NINT3,NINT2,NINT1);
PinListSet(CLKMODPINS,CLKMOD1,CLKMOD2,CLKMOD3);
PinListSet(HAD,HCNTL1,HCNTL0,HBIL,NHRW);
PinListSet(EVENINS,NRS,NHOLD,MPNMC,TMS,TCK,NINT1,NINT3,HBIL,DR,FSR,NHAS,NHDS2,TDI,X2CLKIN,CLKMOD2);
PinListSet(EVENINLEAKINS,EVENINS);
PinListUnSet(EVENINLEAKINS,TMS);
PinListUnSet(EVENINLEAKINS,TCK);
PinListUnSet(EVENINLEAKINS,TDI);
PinListUnSet(EVENINLEAKINS,X2CLKIN);
PinListUnSet(EVENINLEAKINS,CLKMOD2);
PinListUnSet(EVENINLEAKINS,HBIL);
PinListUnSet(EVENINLEAKINS,NHAS);
PinListUnSet(EVENINLEAKINS,NHDS2);
PinListSet(ODDINS,BCLKR,READY,NBIO,TRST,HCNTL0,HCNTL1,HPISEL,NHRW,NINT2,NINT4,NNMI,BDR,CLKR,NHCS,NHDS1,CLKMOD1,CLKMOD3);
PinListSet(ODDINLEAKINS,ODDINS);
PinListUnSet(ODDINLEAKINS,TRST);
PinListUnSet(ODDINLEAKINS,CLKMOD1);
PinListUnSet(ODDINLEAKINS,CLKMOD3);
PinListUnSet(ODDINLEAKINS,HPISEL);
PinListUnSet(ODDINLEAKINS,HCNTL1);
PinListUnSet(ODDINLEAKINS,HCNTL0);
PinListUnSet(ODDINLEAKINS,NHRW);
PinListUnSet(ODDINLEAKINS,NHCS);
PinListUnSet(ODDINLEAKINS,NHDS1);
PinListSet(EVENTRISTATE,BFSR,TOUT,CLKX,NIAQ,D14,D12,D10,D8,D6,D4,D2,D0,A0,A2,A4,A6,A8,A10,A12,A14,HRDY,NRD,NWE,NDS,NPS,NSTRB,NBR,TDO,FSX,BFSX,DX,NHOLDA,CLKOUT);
PinListUnSet(EVENTRISTATE,NBR);
PinListSet(ODDTRISTATE,NHINT,BCLKX,D15,D13,D11,D9,D7,D5,D3,D1,A1,A3,A5,A7,A9,A11,A13,A15,HD0,HD1,HD2,NIS,RNW,HD3,X1,HD4,HD5,HD6,HD7,BDX,XF,NIACK);
PinListUnSet(ODDTRISTATE,X1);
PinListSet(ALLTRISTATE,EVENTRISTATE,ODDTRISTATE,EMU0);
PinListSet(ALLINS,EVENINS,ODDINS);
PinListSet(INPUTS,ALLINS);
PinListUnSet(INPUTS,X2CLKIN);
PinListUnSet(INPUTS,CLKMOD1);
PinListUnSet(INPUTS,CLKMOD2);
PinListUnSet(INPUTS,CLKMOD3);
PinListSet(TESTINS,ALLINS,EMU1,EMU0);
PinListUnSet(TESTINS,INUPS);
PinListUnSet(TESTINS,INDOWNS);
PinListSet(TIMINGINS,INPUTS);
PinListUnSet(TIMINGINS,CLKR);
PinListUnSet(TIMINGINS,BCLKR);
PinListUnSet(TIMINGINS,NHOLD);
PinListUnSet(TIMINGINS,HPISEL);
PinListSet(ALLOUTS,NRD,NIS,TDO,DX,NHOLDA,CLKOUT,NIACK,TOUT,NIAQ,NWE,NDS,NPS,X1,BDX,XF,HRDY,NHINT);
PinListSet(ALLINLEAKOUTS,ALLOUTS);
PinListUnSet(ALLINLEAKOUTS,X1);
PinListSet(PTULEAK1,INDOWNS);
PinListSet(PTULEAK2,EMU0,EMU1,X2CLKIN);
PinListSet(PTULEAK3,ODDINLEAKINS,EVENINLEAKINS,CLKMODPINS,INUPS,ODDTRISTATE,EVENTRISTATE,NBR);
PinListSet(IDDQDISCONNECT,INUPS,TRST,NBR,ABUS,RNW,NSTRB,ALLOUTS,HRDY,NHINT,HD7,HD6,HD5,HD4,HD3,HD2,HD1,HD0);
PinListSet(LOOSEOUTS,ALLOUTS);
PinListUnSet(LOOSEOUTS,NRD);
PinListUnSet(LOOSEOUTS,CLKOUT);
PinListSet(TIMINGOUTS,ALLOUTS);
PinListUnSet(TIMINGOUTS,XF);
PinListUnSet(TIMINGOUTS,TOUT);
PinListUnSet(TIMINGOUTS,CLKOUT);
PinListUnSet(TIMINGOUTS,NRD);
PinListUnSet(TIMINGOUTS,DX);
PinListUnSet(TIMINGOUTS,BDX);
PinListUnSet(TIMINGOUTS,NIAQ);
PinListUnSet(TIMINGOUTS,NIACK);
PinListUnSet(TIMINGOUTS,NPS);
PinListUnSet(TIMINGOUTS,NDS);
PinListUnSet(TIMINGOUTS,NIS);
PinListUnSet(TIMINGOUTS,HRDY);
PinListUnSet(TIMINGOUTS,NHINT);
PinListSet(ALLIOS,BFSR,EMU0,CLKX,D14,D12,D10,D8,D6,D4,D2,D0,A0,A2,A4,A6,A8,A10,A12,A14,NSTRB,NBR,RNW,FSX,BFSX,EMU1,BCLKX,D15,D13,D11,D9,D7,D5,D3,D1,A1,A3,A5,A7,A9,A11,A13,A15,HD0,HD1,HD2,HD3,HD4,HD5,HD6,HD7);
PinListSet(ALLINLEAKIOS,ALLIOS);
PinListUnSet(ALLINLEAKIOS,EMU0);
PinListUnSet(ALLINLEAKIOS,EMU1);
PinListSet(TIMINGIOS,ALLIOS);
PinListUnSet(TIMINGIOS,CLKX);
PinListUnSet(TIMINGIOS,BCLKX);
PinListUnSet(TIMINGIOS,FSX);
PinListUnSet(TIMINGIOS,BFSX);
PinListUnSet(TIMINGIOS,NSTRB);
PinListUnSet(TIMINGIOS,DBUS);
PinListUnSet(TIMINGIOS,ABUS);
PinListUnSet(TIMINGIOS,RNW);
PinListUnSet(TIMINGIOS,NBR);
PinListUnSet(TIMINGIOS,HPI_DBUS);
PinListSet(LOOSEIOS,ALLIOS);
PinListUnSet(LOOSEIOS,FSX);
PinListUnSet(LOOSEIOS,BFSX);
PinListUnSet(LOOSEIOS,HPI_DBUS);
PinListSet(MUXPINS,X2CLKIN,CLKOUT,NRD,NSTRB)
PinListSetNull(NCPINS);
PinListSet(FIELD16,NMTESTEN,NOLCS,NOLCM,SYNC);
PinListSet(FIELD15,HPISEL,HRDY,NHCS,NHAS,NHINT,HBIL,NHRW,HCNTL1,HCNTL0,NHDS2,NHDS1);
PinListSet(FIELD14,HD7,HD6,HD5,HD4,HD3,HD2,HD1,HD0);
PinListSet(FIELD13,EMU1,EMU0);
PinListSet(FIELD12,TRST,TMS,TCK,TDI,TDO);
PinListSet(FIELD11,BCLKR,BFSR,BDR,BCLKX,BFSX,BDX);
PinListSet(FIELD10,CLKR,FSR,DR,CLKX,FSX,DX);
PinListSet(FIELD9,NIACK,NIACK,NIAQ,NIAQ,TOUT,XF);
PinListSet(FIELD8,NDS,NPS,NIS);
PinListSet(FIELD7,NSTRB,NSTRB,RNW,NBR);
PinListSet(FIELD6,NRD,NRD,NWE);
PinListSet(FIELD5,A15,A14,A13,A12,A11,A10,A9,A8,A7,A6,A5,A4,A3,A2,A1,A0);
PinListSet(FIELD4,D15,D14,D13,D12,D11,D10,D9,D8,D7,D6,D5,D4,D3,D2,D1,D0);
PinListSet(FIELD3,NNMI,NINT4,NINT3,NINT2,NINT1);
PinListSet(FIELD2,NRS,NBIO,MPNMC,READY,NHOLD,NHOLDA);
PinListSet(FIELD1,X1,CLKMOD1,CLKMOD2,CLKMOD3,X2CLKIN,X2CLKIN,CLKOUT,CLKOUT);
PinListSetNull(noPinList);

